---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/ucschostingacm/public_html/
    - /bin/cp -R src $DEPLOY_PATH
    - /bin/cp index.html $DEPLOY_PATH
    - /bin/cp particlesjs-config.json $DEPLOY_PATH
    - /bin/cp favicon.ico $DEPLOY_PATH